// Real, curated, trilingual prompt decks for "Wahrheit oder Pflicht" /
// "Truth or Dare" / "Verdad o Reto" — 20 truths + 20 dares, no duplicates,
// same meaning across de/en/es.
export const TRUTHS = [
  { de: "Was ist die peinlichste Nachricht in deinem Handy?", en: "What's the most embarrassing text on your phone?", es: "¿Cuál es el mensaje más vergonzoso en tu teléfono?" },
  { de: "Wer aus dieser Runde würdest du am ehesten daten?", en: "Who in this group would you most likely date?", es: "¿Con quién de este grupo saldrías más probablemente?" },
  { de: "Was ist die größte Lüge, die du je erzählt hast?", en: "What's the biggest lie you've ever told?", es: "¿Cuál es la mentira más grande que has dicho?" },
  { de: "Welche App checkst du morgens als Erstes?", en: "Which app do you check first in the morning?", es: "¿Qué app revisas primero por la mañana?" },
  { de: "Was war dein peinlichster Moment in der Schule?", en: "What was your most embarrassing moment at school?", es: "¿Cuál fue tu momento más vergonzoso en el colegio?" },
  { de: "Wen hast du zuletzt heimlich auf Social Media gestalkt?", en: "Who did you last secretly stalk on social media?", es: "¿A quién stalkeaste por última vez en redes sociales?" },
  { de: "Was ist das Unangenehmste, das dir auf einem Date passiert ist?", en: "What's the most awkward thing that's happened to you on a date?", es: "¿Cuál es lo más incómodo que te ha pasado en una cita?" },
  { de: "Welche Notlüge benutzt du am häufigsten?", en: "What white lie do you use most often?", es: "¿Qué mentira piadosa usas más seguido?" },
  { de: "Was würdest du nie öffentlich zugeben, außer jetzt?", en: "What would you never admit publicly, except right now?", es: "¿Qué nunca admitirías en público, excepto ahora?" },
  { de: "Wer in dieser Runde könnte dich am ehesten überreden, etwas Dummes zu tun?", en: "Who in this group could most easily talk you into doing something dumb?", es: "¿Quién de este grupo podría convencerte más fácilmente de hacer una tontería?" },
  { de: "Was ist dein größtes Guilty Pleasure?", en: "What's your biggest guilty pleasure?", es: "¿Cuál es tu mayor placer culposo?" },
  { de: "Welche Nachricht hast du abgeschickt und sofort bereut?", en: "What message did you send and instantly regret?", es: "¿Qué mensaje enviaste y te arrepentiste al instante?" },
  { de: "Was ist das Verrückteste, das du je um 3 Uhr nachts getan hast?", en: "What's the craziest thing you've done at 3am?", es: "¿Qué es lo más loco que has hecho a las 3 de la madrugada?" },
  { de: "Wem in dieser Runde würdest du am ehesten dein Passwort anvertrauen?", en: "Who in this group would you trust with your password?", es: "¿A quién de este grupo le confiarías tu contraseña?" },
  { de: "Was war dein peinlichster Spitzname?", en: "What was your most embarrassing nickname?", es: "¿Cuál fue tu apodo más vergonzoso?" },
  { de: "Was ist das Peinlichste, das du je gepostet hast?", en: "What's the most embarrassing thing you've ever posted?", es: "¿Qué es lo más vergonzoso que has publicado?" },
  { de: "Welche Serie schaust du heimlich, ohne es zuzugeben?", en: "What show do you secretly watch without admitting it?", es: "¿Qué serie ves a escondidas sin admitirlo?" },
  { de: "Was ist die unangenehmste Verabredung, die du je hattest?", en: "What's the most awkward date you've ever been on?", es: "¿Cuál ha sido tu cita más incómoda?" },
  { de: "Wen in dieser Runde würdest du am ehesten um einen Gefallen bitten, den du nicht zurückzahlen kannst?", en: "Who in this group would you most likely ask for a favor you can't repay?", es: "¿A quién de este grupo le pedirías un favor que no puedes devolver?" },
  { de: "Was ist das Ungewöhnlichste, wofür du je Geld ausgegeben hast?", en: "What's the strangest thing you've ever spent money on?", es: "¿Cuál es lo más raro en lo que has gastado dinero?" },
];

export const DARES = [
  { de: "Mach 10 Liegestütze — sofort.", en: "Do 10 push-ups — right now.", es: "Haz 10 flexiones — ahora mismo." },
  { de: "Tanze 20 Sekunden ohne Musik, alle schauen zu.", en: "Dance for 20 seconds with no music, everyone watching.", es: "Baila 20 segundos sin música, todos mirando." },
  { de: "Lass dir von der Gruppe ein Wort geben und erfinde einen Rap dazu.", en: "Have the group give you a word and freestyle a rap about it.", es: "Deja que el grupo te dé una palabra e improvisa un rap con ella." },
  { de: "Sprich für die nächsten drei Minuten mit einem Akzent deiner Wahl.", en: "Speak in an accent of your choice for the next three minutes.", es: "Habla con el acento que quieras durante los próximos tres minutos." },
  { de: "Ruf jemanden an und sing die ersten Zeilen eines Liedes vor.", en: "Call someone and sing the first lines of a song to them.", es: "Llama a alguien y cántale las primeras líneas de una canción." },
  { de: "Lass die Gruppe dein nächstes Story-Bild aussuchen.", en: "Let the group pick your next story photo.", es: "Deja que el grupo elija tu próxima foto de historia." },
  { de: "Mach ein Kompliment an jede Person in der Runde — ohne zu lachen.", en: "Give every person in the group a compliment — without laughing.", es: "Hazle un cumplido a cada persona del grupo — sin reírte." },
  { de: "Erzähl einen Witz. Lacht niemand, trinkst du extra.", en: "Tell a joke. If nobody laughs, you drink extra.", es: "Cuenta un chiste. Si nadie se ríe, bebes extra." },
  { de: "Tausche für die nächste Runde einen Gegenstand mit deinem Nachbarn.", en: "Swap an item with your neighbor for the rest of the round.", es: "Intercambia un objeto con tu vecino/a por el resto de la ronda." },
  { de: "Imitiere eine Person aus der Runde, die anderen raten wer.", en: "Impersonate someone in the group, everyone else guesses who.", es: "Imita a alguien del grupo, los demás adivinan a quién." },
  { de: "Erzähl die Handlung deines Lieblingsfilms nur mit Gesten.", en: "Act out the plot of your favorite movie using only gestures.", es: "Actúa la trama de tu película favorita solo con gestos." },
  { de: "Lass dir von jemandem die Schuhe binden — mit geschlossenen Augen.", en: "Have someone tie your shoes — with your eyes closed.", es: "Deja que alguien te ate los zapatos — con los ojos cerrados." },
  { de: "Sing den Refrain eines Liedes, das dir gerade einfällt.", en: "Sing the chorus of whatever song comes to mind first.", es: "Canta el estribillo de la primera canción que se te ocurra." },
  { de: "Halte 30 Sekunden lang Blickkontakt mit deinem Nachbarn, ohne zu lachen.", en: "Hold eye contact with your neighbor for 30 seconds without laughing.", es: "Mantén contacto visual con tu vecino/a 30 segundos sin reírte." },
  { de: "Erfinde spontan ein Trinklied für diese Runde.", en: "Make up a drinking song for this group on the spot.", es: "Inventa una canción para beber para este grupo, en el momento." },
  { de: "Lass dich von der Gruppe für 2 Minuten fotografieren, wie du posierst.", en: "Let the group photograph you posing for 2 minutes.", es: "Deja que el grupo te fotografíe posando durante 2 minutos." },
  { de: "Erzähl eine Geschichte rückwärts, Satz für Satz.", en: "Tell a story backwards, sentence by sentence.", es: "Cuenta una historia al revés, frase por frase." },
  { de: "Mach für die nächste Runde Ansagen wie ein Sportkommentator.", en: "Do sports-commentator style commentary for the next round.", es: "Comenta la siguiente ronda como un comentarista deportivo." },
  { de: "Lass jemanden aus der Gruppe dein nächstes Getränk bestellen — du trinkst es, ohne zu fragen was es ist.", en: "Let someone in the group order your next drink — you drink it without asking what it is.", es: "Deja que alguien del grupo pida tu próxima bebida — la bebes sin preguntar qué es." },
  { de: "Halte eine 30-Sekunden-Werbung für einen Gegenstand aus deiner Tasche.", en: "Give a 30-second infomercial for an object from your pocket or bag.", es: "Haz un anuncio de 30 segundos de un objeto de tu bolsillo o bolso." },
];
