// Real, curated prompt deck for "Ich hab noch nie" — no placeholders.
export const NIEMALS_PROMPTS = [
  { cat: "mild", text: "…einen Chef angelogen, um früher gehen zu können." },
  { cat: "mild", text: "…in der Öffentlichkeit bin ich hingefallen." },
  { cat: "mild", text: "…eine Nachricht an die falsche Person geschickt." },
  { cat: "mild", text: "…bei einem Date so getan, als würde ich zuhören." },
  { cat: "mild", text: "…aus Versehen einen Alarm ausgelöst." },
  { cat: "mild", text: "…ein Kino verlassen, weil der Film so schlecht war." },
  { cat: "mild", text: "…unter falschem Namen einen Tisch reserviert." },
  { cat: "mild", text: "…betrunken eine wichtige Nachricht getippt, aber nie abgeschickt." },
  { cat: "mild", text: "…eine Prüfung ohne zu lernen bestanden." },
  { cat: "mild", text: "…jemanden auf Social Media heimlich gestalkt." },
  { cat: "mild", text: "…auf der Arbeit oder in der Uni eingeschlafen." },
  { cat: "mild", text: "…beim Karaoke komplett versagt." },
  { cat: "mild", text: "…einen Trip abgesagt, weil ich zu faul zum Packen war." },
  { cat: "mild", text: "…in der Schule geschummelt." },
  { cat: "mild", text: "…vor Publikum über meine eigenen Füße gestolpert." },
  { cat: "mild", text: "…ein Geschenk weiterverschenkt, das ich selbst bekommen habe." },
  { cat: "mild", text: "…so getan, als hätte ich eine Nachricht nicht gesehen." },
  { cat: "mild", text: "…ein Foto von mir stark bearbeitet, bevor ich es gepostet habe." },
  { cat: "mild", text: "…mich verlaufen, obwohl ich wusste, wo ich war." },
  { cat: "mild", text: "…bei einem Quiz geschummelt, um zu gewinnen." },
  { cat: "spicy", text: "…mit meinem Ex geschrieben, obwohl ich es nicht wollte." },
  { cat: "spicy", text: "…ein Date direkt nach dem ersten Treffen abgesagt." },
  { cat: "spicy", text: "…jemanden in dieser Runde schon mal attraktiv gefunden." },
  { cat: "spicy", text: "…eine Beziehung nur wegen der Bequemlichkeit fortgesetzt." },
  { cat: "spicy", text: "…jemanden geghostet." },
  { cat: "spicy", text: "…bei einem One-Night-Stand am nächsten Morgen bereut, geblieben zu sein." },
  { cat: "spicy", text: "…heimlich jemanden aus dieser Runde gegoogelt." },
  { cat: "spicy", text: "…eine Notlüge benutzt, um ein Date zu beenden." },
  { cat: "spicy", text: "…schon mal jemandem aus Mitleid geantwortet." },
  { cat: "spicy", text: "…eine Dating-App gleichzeitig mit mehreren Leuten genutzt." },
];
