// Real, curated, trilingual prompt deck for "Ich hab noch nie" / "Never Have I
// Ever" / "Yo Nunca" — 40 unique prompts (20 mild + 20 spicy), no duplicates,
// same meaning across de/en/es so the deck stays identical when the language
// is switched mid-session.
export const NIEMALS_PROMPTS = [
  { cat: "mild", de: "…einen Chef angelogen, um früher gehen zu können.", en: "…lied to a boss to leave work early.", es: "…le mentí a un jefe para salir antes del trabajo." },
  { cat: "mild", de: "…in der Öffentlichkeit hingefallen.", en: "…fallen down in public.", es: "…me caí en público." },
  { cat: "mild", de: "…eine Nachricht an die falsche Person geschickt.", en: "…sent a text to the wrong person.", es: "…envié un mensaje a la persona equivocada." },
  { cat: "mild", de: "…bei einem Date so getan, als würde ich zuhören.", en: "…pretended to listen on a date.", es: "…fingí escuchar en una cita." },
  { cat: "mild", de: "…aus Versehen einen Alarm ausgelöst.", en: "…accidentally set off an alarm.", es: "…activé una alarma sin querer." },
  { cat: "mild", de: "…ein Kino verlassen, weil der Film so schlecht war.", en: "…walked out of a movie because it was that bad.", es: "…salí de un cine porque la película era pésima." },
  { cat: "mild", de: "…unter falschem Namen einen Tisch reserviert.", en: "…made a reservation under a fake name.", es: "…reservé una mesa con un nombre falso." },
  { cat: "mild", de: "…betrunken eine wichtige Nachricht getippt, aber nie abgeschickt.", en: "…typed an important message while drunk but never sent it.", es: "…escribí un mensaje importante borracho/a pero nunca lo envié." },
  { cat: "mild", de: "…eine Prüfung ohne zu lernen bestanden.", en: "…passed an exam without studying.", es: "…aprobé un examen sin estudiar." },
  { cat: "mild", de: "…jemanden auf Social Media heimlich gestalkt.", en: "…secretly stalked someone on social media.", es: "…stalkeé a alguien en redes sociales en secreto." },
  { cat: "mild", de: "…auf der Arbeit oder in der Uni eingeschlafen.", en: "…fallen asleep at work or in class.", es: "…me quedé dormido/a en el trabajo o en clase." },
  { cat: "mild", de: "…beim Karaoke komplett versagt.", en: "…completely bombed at karaoke.", es: "…fracasé por completo cantando karaoke." },
  { cat: "mild", de: "…einen Trip abgesagt, weil ich zu faul zum Packen war.", en: "…cancelled a trip because I was too lazy to pack.", es: "…cancelé un viaje por pereza de hacer la maleta." },
  { cat: "mild", de: "…in der Schule geschummelt.", en: "…cheated on a test at school.", es: "…copié en un examen en el colegio." },
  { cat: "mild", de: "…vor Publikum über meine eigenen Füße gestolpert.", en: "…tripped over my own feet in front of people.", es: "…tropecé con mis propios pies delante de gente." },
  { cat: "mild", de: "…ein Geschenk weiterverschenkt, das ich selbst bekommen habe.", en: "…regifted something I received myself.", es: "…regalé algo que a mí me habían regalado." },
  { cat: "mild", de: "…so getan, als hätte ich eine Nachricht nicht gesehen.", en: "…pretended I hadn't seen a message.", es: "…fingí no haber visto un mensaje." },
  { cat: "mild", de: "…ein Foto von mir stark bearbeitet, bevor ich es gepostet habe.", en: "…heavily edited a photo of myself before posting it.", es: "…edité mucho una foto mía antes de publicarla." },
  { cat: "mild", de: "…mich verlaufen, obwohl ich wusste, wo ich war.", en: "…gotten lost even though I knew where I was.", es: "…me perdí aunque sabía dónde estaba." },
  { cat: "mild", de: "…bei einem Quiz geschummelt, um zu gewinnen.", en: "…cheated at a quiz just to win.", es: "…hice trampa en un concurso solo para ganar." },

  { cat: "spicy", de: "…mit meinem Ex geschrieben, obwohl ich es nicht wollte.", en: "…texted my ex even though I didn't want to.", es: "…le escribí a mi ex aunque no quería." },
  { cat: "spicy", de: "…ein Date direkt nach dem ersten Treffen abgesagt.", en: "…cancelled a date right after the first meeting.", es: "…cancelé una cita justo después del primer encuentro." },
  { cat: "spicy", de: "…jemanden in dieser Runde schon mal attraktiv gefunden.", en: "…found someone in this group attractive.", es: "…encontré atractivo/a a alguien de este grupo." },
  { cat: "spicy", de: "…eine Beziehung nur wegen der Bequemlichkeit fortgesetzt.", en: "…stayed in a relationship purely out of convenience.", es: "…seguí en una relación solo por comodidad." },
  { cat: "spicy", de: "…jemanden geghostet.", en: "…ghosted someone.", es: "…le hice ghosting a alguien." },
  { cat: "spicy", de: "…bei einem One-Night-Stand am nächsten Morgen bereut, geblieben zu sein.", en: "…regretted staying the morning after a one-night stand.", es: "…me arrepentí de quedarme la mañana después de un one-night-stand." },
  { cat: "spicy", de: "…heimlich jemanden aus dieser Runde gegoogelt.", en: "…secretly googled someone in this group.", es: "…busqué en secreto a alguien de este grupo en internet." },
  { cat: "spicy", de: "…eine Notlüge benutzt, um ein Date zu beenden.", en: "…used a white lie to end a date early.", es: "…usé una mentira piadosa para terminar una cita." },
  { cat: "spicy", de: "…schon mal jemandem aus Mitleid geantwortet.", en: "…replied to someone out of pity.", es: "…le respondí a alguien por lástima." },
  { cat: "spicy", de: "…eine Dating-App gleichzeitig mit mehreren Leuten genutzt.", en: "…used multiple dating apps with several people at once.", es: "…usé varias apps de citas con varias personas a la vez." },
  { cat: "spicy", de: "…mit jemandem geflirtet, nur um ein Getränk spendiert zu bekommen.", en: "…flirted with someone just to get a free drink.", es: "…coqueteé con alguien solo para que me invitaran una bebida." },
  { cat: "spicy", de: "…ein zweites Date abgesagt, weil das erste zu langweilig war.", en: "…cancelled a second date because the first was too boring.", es: "…cancelé una segunda cita porque la primera fue muy aburrida." },
  { cat: "spicy", de: "…jemanden aus reiner Neugier auf ein Date eingeladen.", en: "…asked someone out purely out of curiosity.", es: "…invité a salir a alguien solo por curiosidad." },
  { cat: "spicy", de: "…über meinen Beziehungsstatus gelogen, um Aufmerksamkeit zu vermeiden.", en: "…lied about my relationship status to avoid attention.", es: "…mentí sobre mi estado sentimental para evitar atención." },
  { cat: "spicy", de: "…während einer Beziehung mit jemand anderem geflirtet.", en: "…flirted with someone else while in a relationship.", es: "…coqueteé con alguien más estando en una relación." },
  { cat: "spicy", de: "…ein Foto gelöscht, weil ein Ex noch drauf war.", en: "…deleted a photo because an ex was still in it.", es: "…borré una foto porque salía un ex." },
  { cat: "spicy", de: "…absichtlich eine Nachricht ignoriert, um interessanter zu wirken.", en: "…deliberately ignored a message to seem more interesting.", es: "…ignoré un mensaje a propósito para parecer más interesante." },
  { cat: "spicy", de: "…jemanden aus dieser Runde in einem Traum geküsst.", en: "…dreamed about kissing someone in this group.", es: "…soñé con besar a alguien de este grupo." },
  { cat: "spicy", de: "…eine Verabredung nur wegen des Essens durchgezogen.", en: "…went on a date purely for the food.", es: "…fui a una cita solo por la comida." },
  { cat: "spicy", de: "…schon mal aus Langeweile mit einem Ex geflirtet.", en: "…flirted with an ex out of boredom.", es: "…coqueteé con un ex por aburrimiento." },
];
